export const CATEGORIES = [
  "Startup & Business Ideas",
  "Product & Invention",
  "Software & Technology",
  "AI & Automation",
  "Marketing & Growth",
  "Branding & Identity",
  "Content & Creator Economy",
  "Writing & Storytelling",
  "Design & Visual Arts",
  "Music & Audio",
  "Web3 & Blockchain",
  "Finance & Monetization",
  "Education & Knowledge",
  "Health & Wellness",
  "Personal Development & Lifestyle",
  "Experimental & Wildcard",
] as const;

export const CATEGORY_META: Record<string, { name: string; slug: string; description: string; icon: string }> = {
  "Startup & Business Ideas": {
    name: "Startup & Business Ideas",
    slug: "startup-business-ideas",
    description: "Venture concepts, business models, and entrepreneurial strategies from experienced operators.",
    icon: "Rocket",
  },
  "Product & Invention": {
    name: "Product & Invention",
    slug: "product-invention",
    description: "Physical products, consumer electronics, hardware, and innovative invention concepts.",
    icon: "Package",
  },
  "Software & Technology": {
    name: "Software & Technology",
    slug: "software-technology",
    description: "Cutting-edge tech insights, architecture patterns, scripts, and engineering strategies from industry professionals.",
    icon: "Code",
  },
  "AI & Automation": {
    name: "AI & Automation",
    slug: "ai-automation",
    description: "AI applications, prompt engineering, agents, automation workflows, and machine learning concepts.",
    icon: "Bot",
  },
  "Marketing & Growth": {
    name: "Marketing & Growth",
    slug: "marketing-growth",
    description: "Growth hacks, SEO tactics, conversion strategies, and campaign insights from top marketers.",
    icon: "TrendingUp",
  },
  "Branding & Identity": {
    name: "Branding & Identity",
    slug: "branding-identity",
    description: "Brand positioning, naming, visual identity, and strategic brand development concepts.",
    icon: "Fingerprint",
  },
  "Content & Creator Economy": {
    name: "Content & Creator Economy",
    slug: "content-creator-economy",
    description: "Content creation secrets, audience growth strategies, and creator monetization insights.",
    icon: "Video",
  },
  "Writing & Storytelling": {
    name: "Writing & Storytelling",
    slug: "writing-storytelling",
    description: "Novel concepts, screenplay ideas, worldbuilding, narrative structures, and copywriting frameworks.",
    icon: "PenTool",
  },
  "Design & Visual Arts": {
    name: "Design & Visual Arts",
    slug: "design-visual-arts",
    description: "UX patterns, creative workflows, design systems, and visual strategies from seasoned designers.",
    icon: "Palette",
  },
  "Music & Audio": {
    name: "Music & Audio",
    slug: "music-audio",
    description: "Song concepts, production techniques, audio branding, and music business models.",
    icon: "Music",
  },
  "Web3 & Blockchain": {
    name: "Web3 & Blockchain",
    slug: "web3-blockchain",
    description: "Token models, DeFi protocols, DAOs, NFTs, and decentralized application concepts.",
    icon: "Link",
  },
  "Finance & Monetization": {
    name: "Finance & Monetization",
    slug: "finance-monetization",
    description: "Investment strategies, financial planning insights, revenue models, and money management tactics.",
    icon: "DollarSign",
  },
  "Education & Knowledge": {
    name: "Education & Knowledge",
    slug: "education-knowledge",
    description: "Teaching methods, curriculum insights, and learning frameworks from education professionals.",
    icon: "GraduationCap",
  },
  "Health & Wellness": {
    name: "Health & Wellness",
    slug: "health-wellness",
    description: "Wellness insights, fitness strategies, health optimization tips, and mental health innovations.",
    icon: "Heart",
  },
  "Personal Development & Lifestyle": {
    name: "Personal Development & Lifestyle",
    slug: "personal-development-lifestyle",
    description: "Productivity systems, habit design, goal-setting, career strategy, and life design concepts.",
    icon: "Compass",
  },
  "Experimental & Wildcard": {
    name: "Experimental & Wildcard",
    slug: "experimental-wildcard",
    description: "Cross-domain mashups, thought experiments, futurism, and ideas that defy classification.",
    icon: "Sparkles",
  },
};

export const SUBCATEGORIES: Record<string, Array<{ name: string; slug: string }>> = {
  "Startup & Business Ideas": [
    { name: "SaaS Business Ideas", slug: "saas-business-ideas" },
    { name: "Marketplace & Platform Concepts", slug: "marketplace-platform-concepts" },
    { name: "Subscription Business Models", slug: "subscription-business-models" },
    { name: "Franchise & Licensing Concepts", slug: "franchise-licensing-concepts" },
    { name: "Social Enterprise & Impact Ventures", slug: "social-enterprise-impact-ventures" },
    { name: "Local & Small Business Ideas", slug: "local-small-business-ideas" },
    { name: "E-Commerce & DTC Concepts", slug: "ecommerce-dtc-concepts" },
    { name: "Service-Based Business Models", slug: "service-based-business-models" },
    { name: "B2B Business Ideas", slug: "b2b-business-ideas" },
    { name: "Micro-Business & Side Hustle Concepts", slug: "micro-business-side-hustle-concepts" },
    { name: "Industry Disruption Strategies", slug: "industry-disruption-strategies" },
    { name: "Partnership & Joint Venture Frameworks", slug: "partnership-joint-venture-frameworks" },
    { name: "Pivot & Repositioning Strategies", slug: "pivot-repositioning-strategies" },
    { name: "Niche Market Opportunities", slug: "niche-market-opportunities" },
    { name: "Business Model Innovations", slug: "business-model-innovations" },
  ],
  "Product & Invention": [
    { name: "Physical Product Concepts", slug: "physical-product-concepts" },
    { name: "Consumer Electronics Ideas", slug: "consumer-electronics-ideas" },
    { name: "Hardware & IoT Inventions", slug: "hardware-iot-inventions" },
    { name: "Sustainable & Eco Products", slug: "sustainable-eco-products" },
    { name: "Food & Beverage Concepts", slug: "food-beverage-concepts" },
    { name: "Fashion & Wearable Ideas", slug: "fashion-wearable-ideas" },
    { name: "Home & Living Products", slug: "home-living-products" },
    { name: "Toy & Game Inventions", slug: "toy-game-inventions" },
    { name: "Medical Device Concepts", slug: "medical-device-concepts" },
    { name: "Packaging & Material Innovations", slug: "packaging-material-innovations" },
    { name: "Digital Product Ideas", slug: "digital-product-ideas" },
    { name: "Accessibility & Assistive Products", slug: "accessibility-assistive-products" },
    { name: "Pet & Animal Products", slug: "pet-animal-products" },
    { name: "Travel & Outdoor Gear Concepts", slug: "travel-outdoor-gear-concepts" },
  ],
  "Software & Technology": [
    { name: "Mobile App Ideas", slug: "mobile-app-ideas" },
    { name: "Web Application Concepts", slug: "web-application-concepts" },
    { name: "Micro-SaaS Ideas", slug: "micro-saas-ideas" },
    { name: "Developer Tools & Libraries", slug: "developer-tools-libraries" },
    { name: "API & Integration Concepts", slug: "api-integration-concepts" },
    { name: "Browser Extension Ideas", slug: "browser-extension-ideas" },
    { name: "Database & Architecture Patterns", slug: "database-architecture-patterns" },
    { name: "Algorithm & Data Structure Innovations", slug: "algorithm-data-structure-innovations" },
    { name: "Cybersecurity Concepts", slug: "cybersecurity-concepts" },
    { name: "DevOps & Infrastructure Ideas", slug: "devops-infrastructure-ideas" },
    { name: "Open-Source Project Concepts", slug: "open-source-project-concepts" },
    { name: "No-Code & Low-Code Solutions", slug: "no-code-low-code-solutions" },
    { name: "Desktop Software Ideas", slug: "desktop-software-ideas" },
    { name: "CLI & Automation Tool Concepts", slug: "cli-automation-tool-concepts" },
    { name: "Gaming & Interactive Software", slug: "gaming-interactive-software" },
    { name: "Search & Discovery Systems", slug: "search-discovery-systems" },
  ],
  "AI & Automation": [
    { name: "AI Application Ideas", slug: "ai-application-ideas" },
    { name: "Prompt Engineering & Prompt Libraries", slug: "prompt-engineering-prompt-libraries" },
    { name: "AI Agent & Workflow Concepts", slug: "ai-agent-workflow-concepts" },
    { name: "Machine Learning Model Ideas", slug: "machine-learning-model-ideas" },
    { name: "Natural Language Processing Concepts", slug: "natural-language-processing-concepts" },
    { name: "Computer Vision Applications", slug: "computer-vision-applications" },
    { name: "Generative AI Use Cases", slug: "generative-ai-use-cases" },
    { name: "AI-Powered Business Tools", slug: "ai-powered-business-tools" },
    { name: "Chatbot & Conversational AI Ideas", slug: "chatbot-conversational-ai-ideas" },
    { name: "Robotic Process Automation (RPA)", slug: "robotic-process-automation-rpa" },
    { name: "AI for Creative Industries", slug: "ai-for-creative-industries" },
    { name: "Data Pipeline & ETL Concepts", slug: "data-pipeline-etl-concepts" },
    { name: "Predictive Analytics Frameworks", slug: "predictive-analytics-frameworks" },
    { name: "AI Ethics & Governance Frameworks", slug: "ai-ethics-governance-frameworks" },
    { name: "Voice AI & Speech Applications", slug: "voice-ai-speech-applications" },
    { name: "AI Training Data Strategies", slug: "ai-training-data-strategies" },
  ],
  "Marketing & Growth": [
    { name: "Growth Hacking Strategies", slug: "growth-hacking-strategies" },
    { name: "Viral Marketing Concepts", slug: "viral-marketing-concepts" },
    { name: "SEO & Organic Growth Frameworks", slug: "seo-organic-growth-frameworks" },
    { name: "Email Marketing Strategies", slug: "email-marketing-strategies" },
    { name: "Social Media Campaign Ideas", slug: "social-media-campaign-ideas" },
    { name: "Influencer Marketing Concepts", slug: "influencer-marketing-concepts" },
    { name: "Community-Led Growth Strategies", slug: "community-led-growth-strategies" },
    { name: "Referral & Affiliate Program Designs", slug: "referral-affiliate-program-designs" },
    { name: "Paid Advertising Strategies", slug: "paid-advertising-strategies" },
    { name: "Product-Led Growth Frameworks", slug: "product-led-growth-frameworks" },
    { name: "Content Marketing Systems", slug: "content-marketing-systems" },
    { name: "Conversion Optimization Ideas", slug: "conversion-optimization-ideas" },
    { name: "Launch & Go-to-Market Strategies", slug: "launch-go-to-market-strategies" },
    { name: "Guerrilla & Unconventional Marketing", slug: "guerrilla-unconventional-marketing" },
    { name: "Retention & Loyalty Strategies", slug: "retention-loyalty-strategies" },
    { name: "Partnership & Co-Marketing Ideas", slug: "partnership-co-marketing-ideas" },
  ],
  "Branding & Identity": [
    { name: "Brand Name & Naming Concepts", slug: "brand-name-naming-concepts" },
    { name: "Brand Positioning Strategies", slug: "brand-positioning-strategies" },
    { name: "Tagline & Slogan Ideas", slug: "tagline-slogan-ideas" },
    { name: "Brand Story & Narrative Frameworks", slug: "brand-story-narrative-frameworks" },
    { name: "Visual Identity Directions", slug: "visual-identity-directions" },
    { name: "Brand Architecture Strategies", slug: "brand-architecture-strategies" },
    { name: "Tone of Voice Frameworks", slug: "tone-of-voice-frameworks" },
    { name: "Rebranding & Refresh Strategies", slug: "rebranding-refresh-strategies" },
    { name: "Personal Branding Frameworks", slug: "personal-branding-frameworks" },
    { name: "Cultural & Purpose-Driven Branding", slug: "cultural-purpose-driven-branding" },
    { name: "Luxury & Premium Brand Concepts", slug: "luxury-premium-brand-concepts" },
    { name: "Brand Experience & Sensory Design", slug: "brand-experience-sensory-design" },
    { name: "Employer Branding Strategies", slug: "employer-branding-strategies" },
  ],
  "Content & Creator Economy": [
    { name: "YouTube Channel Concepts", slug: "youtube-channel-concepts" },
    { name: "Podcast Ideas & Formats", slug: "podcast-ideas-formats" },
    { name: "Newsletter & Publication Concepts", slug: "newsletter-publication-concepts" },
    { name: "TikTok & Short-Form Content Strategies", slug: "tiktok-short-form-content-strategies" },
    { name: "Creator Monetization Models", slug: "creator-monetization-models" },
    { name: "Online Community Concepts", slug: "online-community-concepts" },
    { name: "Digital Course & Workshop Ideas", slug: "digital-course-workshop-ideas" },
    { name: "Membership & Patreon-Style Models", slug: "membership-patreon-style-models" },
    { name: "Content Repurposing Frameworks", slug: "content-repurposing-frameworks" },
    { name: "Audience Building Strategies", slug: "audience-building-strategies" },
    { name: "Live Streaming Concepts", slug: "live-streaming-concepts" },
    { name: "UGC & Collaborative Content Ideas", slug: "ugc-collaborative-content-ideas" },
    { name: "Content Calendar & Scheduling Systems", slug: "content-calendar-scheduling-systems" },
    { name: "Creator Tool & Platform Ideas", slug: "creator-tool-platform-ideas" },
    { name: "Sponsorship & Brand Deal Frameworks", slug: "sponsorship-brand-deal-frameworks" },
  ],
  "Writing & Storytelling": [
    { name: "Novel & Book Concepts", slug: "novel-book-concepts" },
    { name: "Screenplay & Script Ideas", slug: "screenplay-script-ideas" },
    { name: "Short Story Seeds", slug: "short-story-seeds" },
    { name: "Worldbuilding & Universe Designs", slug: "worldbuilding-universe-designs" },
    { name: "Character Concepts & Archetypes", slug: "character-concepts-archetypes" },
    { name: "Plot Structures & Narrative Blueprints", slug: "plot-structures-narrative-blueprints" },
    { name: "Poetry & Lyrical Concepts", slug: "poetry-lyrical-concepts" },
    { name: "Non-Fiction Book Ideas", slug: "non-fiction-book-ideas" },
    { name: "Comedy & Satire Concepts", slug: "comedy-satire-concepts" },
    { name: "Interactive & Branching Narrative Ideas", slug: "interactive-branching-narrative-ideas" },
    { name: "Copywriting Frameworks", slug: "copywriting-frameworks" },
    { name: "Journalism & Essay Concepts", slug: "journalism-essay-concepts" },
    { name: "Game Narrative & Lore Concepts", slug: "game-narrative-lore-concepts" },
    { name: "Speech & Presentation Frameworks", slug: "speech-presentation-frameworks" },
    { name: "Anthology & Series Structures", slug: "anthology-series-structures" },
  ],
  "Design & Visual Arts": [
    { name: "UI/UX Design Concepts", slug: "ui-ux-design-concepts" },
    { name: "Graphic Design Directions", slug: "graphic-design-directions" },
    { name: "Illustration & Art Concepts", slug: "illustration-art-concepts" },
    { name: "Motion Design & Animation Ideas", slug: "motion-design-animation-ideas" },
    { name: "3D & Spatial Design Concepts", slug: "3d-spatial-design-concepts" },
    { name: "Photography Project Ideas", slug: "photography-project-ideas" },
    { name: "Architecture & Interior Design Concepts", slug: "architecture-interior-design-concepts" },
    { name: "Fashion & Textile Design Ideas", slug: "fashion-textile-design-ideas" },
    { name: "Design System Frameworks", slug: "design-system-frameworks" },
    { name: "Generative & Algorithmic Art Concepts", slug: "generative-algorithmic-art-concepts" },
    { name: "Typographic & Lettering Concepts", slug: "typographic-lettering-concepts" },
    { name: "Environmental & Experience Design", slug: "environmental-experience-design" },
    { name: "Data Visualization Ideas", slug: "data-visualization-ideas" },
    { name: "Game Art & Asset Concepts", slug: "game-art-asset-concepts" },
  ],
  "Music & Audio": [
    { name: "Song & Composition Concepts", slug: "song-composition-concepts" },
    { name: "Album & EP Themes", slug: "album-ep-themes" },
    { name: "Sound Design Ideas", slug: "sound-design-ideas" },
    { name: "Audio Branding & Sonic Logos", slug: "audio-branding-sonic-logos" },
    { name: "Music Production Techniques", slug: "music-production-techniques" },
    { name: "Film & Game Scoring Concepts", slug: "film-game-scoring-concepts" },
    { name: "Podcast Audio Formats", slug: "podcast-audio-formats" },
    { name: "Music Business & Label Models", slug: "music-business-label-models" },
    { name: "AI Music & Generative Audio Ideas", slug: "ai-music-generative-audio-ideas" },
    { name: "Live Performance Concepts", slug: "live-performance-concepts" },
    { name: "Music Collaboration Frameworks", slug: "music-collaboration-frameworks" },
    { name: "Sample & Loop Library Concepts", slug: "sample-loop-library-concepts" },
  ],
  "Web3 & Blockchain": [
    { name: "Token & Tokenomics Models", slug: "token-tokenomics-models" },
    { name: "DeFi Protocol Concepts", slug: "defi-protocol-concepts" },
    { name: "DAO Structures & Governance Models", slug: "dao-structures-governance-models" },
    { name: "NFT Utility & Collection Ideas", slug: "nft-utility-collection-ideas" },
    { name: "Smart Contract Concepts", slug: "smart-contract-concepts" },
    { name: "Decentralized App (dApp) Ideas", slug: "decentralized-app-dapp-ideas" },
    { name: "Blockchain Gaming Concepts", slug: "blockchain-gaming-concepts" },
    { name: "Digital Identity & Reputation Systems", slug: "digital-identity-reputation-systems" },
    { name: "Decentralized Social Media Concepts", slug: "decentralized-social-media-concepts" },
    { name: "Real-World Asset (RWA) Tokenization Ideas", slug: "real-world-asset-rwa-tokenization-ideas" },
    { name: "Cross-Chain & Interoperability Concepts", slug: "cross-chain-interoperability-concepts" },
    { name: "Privacy & Zero-Knowledge Applications", slug: "privacy-zero-knowledge-applications" },
    { name: "Creator Royalty & Licensing Models", slug: "creator-royalty-licensing-models" },
  ],
  "Finance & Monetization": [
    { name: "Revenue Model Blueprints", slug: "revenue-model-blueprints" },
    { name: "Pricing Strategy Frameworks", slug: "pricing-strategy-frameworks" },
    { name: "Fintech Product Concepts", slug: "fintech-product-concepts" },
    { name: "Investment & Trading Theses", slug: "investment-trading-theses" },
    { name: "Passive Income Models", slug: "passive-income-models" },
    { name: "Crowdfunding & Fundraising Strategies", slug: "crowdfunding-fundraising-strategies" },
    { name: "Real Estate Investment Concepts", slug: "real-estate-investment-concepts" },
    { name: "Paywall & Gating Strategies", slug: "paywall-gating-strategies" },
    { name: "Freemium & Upselling Frameworks", slug: "freemium-upselling-frameworks" },
    { name: "Financial Literacy & Tool Ideas", slug: "financial-literacy-tool-ideas" },
    { name: "Insurance & Risk Model Concepts", slug: "insurance-risk-model-concepts" },
    { name: "Multi-Sided Marketplace Economics", slug: "multi-sided-marketplace-economics" },
    { name: "Unit Economics Frameworks", slug: "unit-economics-frameworks" },
  ],
  "Education & Knowledge": [
    { name: "Online Course Concepts", slug: "online-course-concepts" },
    { name: "EdTech Product Ideas", slug: "edtech-product-ideas" },
    { name: "Curriculum & Syllabus Designs", slug: "curriculum-syllabus-designs" },
    { name: "Workshop & Bootcamp Formats", slug: "workshop-bootcamp-formats" },
    { name: "Learning Gamification Frameworks", slug: "learning-gamification-frameworks" },
    { name: "Corporate Training Concepts", slug: "corporate-training-concepts" },
    { name: "Children & Youth Education Ideas", slug: "children-youth-education-ideas" },
    { name: "Tutoring & Mentorship Models", slug: "tutoring-mentorship-models" },
    { name: "Language Learning Concepts", slug: "language-learning-concepts" },
    { name: "Knowledge Management Systems", slug: "knowledge-management-systems" },
    { name: "Research & Academic Frameworks", slug: "research-academic-frameworks" },
    { name: "Skill Assessment & Certification Ideas", slug: "skill-assessment-certification-ideas" },
    { name: "Micro-Learning & Bite-Size Content Systems", slug: "micro-learning-bite-size-content-systems" },
  ],
  "Health & Wellness": [
    { name: "HealthTech & MedTech Concepts", slug: "healthtech-medtech-concepts" },
    { name: "Mental Health & Therapy Innovations", slug: "mental-health-therapy-innovations" },
    { name: "Fitness & Exercise Program Ideas", slug: "fitness-exercise-program-ideas" },
    { name: "Nutrition & Diet Frameworks", slug: "nutrition-diet-frameworks" },
    { name: "Sleep & Recovery Concepts", slug: "sleep-recovery-concepts" },
    { name: "Wellness App Ideas", slug: "wellness-app-ideas" },
    { name: "Mindfulness & Meditation Concepts", slug: "mindfulness-meditation-concepts" },
    { name: "Corporate Wellness Programs", slug: "corporate-wellness-programs" },
    { name: "Telehealth & Remote Care Models", slug: "telehealth-remote-care-models" },
    { name: "Wearable Health Concepts", slug: "wearable-health-concepts" },
    { name: "Longevity & Biohacking Frameworks", slug: "longevity-biohacking-frameworks" },
    { name: "Holistic & Alternative Wellness Ideas", slug: "holistic-alternative-wellness-ideas" },
  ],
  "Personal Development & Lifestyle": [
    { name: "Productivity Systems & Frameworks", slug: "productivity-systems-frameworks" },
    { name: "Habit Design & Behavior Change Models", slug: "habit-design-behavior-change-models" },
    { name: "Goal-Setting & Planning Frameworks", slug: "goal-setting-planning-frameworks" },
    { name: "Career Strategy & Transition Ideas", slug: "career-strategy-transition-ideas" },
    { name: "Relationship & Communication Frameworks", slug: "relationship-communication-frameworks" },
    { name: "Financial Independence & FIRE Strategies", slug: "financial-independence-fire-strategies" },
    { name: "Journaling & Reflection Systems", slug: "journaling-reflection-systems" },
    { name: "Time Management Architectures", slug: "time-management-architectures" },
    { name: "Decision-Making Frameworks", slug: "decision-making-frameworks" },
    { name: "Travel & Nomad Lifestyle Concepts", slug: "travel-nomad-lifestyle-concepts" },
    { name: "Minimalism & Intentional Living Ideas", slug: "minimalism-intentional-living-ideas" },
    { name: "Parenting & Family Frameworks", slug: "parenting-family-frameworks" },
    { name: "Networking & Social Capital Strategies", slug: "networking-social-capital-strategies" },
    { name: "Philosophy & Life Design Concepts", slug: "philosophy-life-design-concepts" },
  ],
  "Experimental & Wildcard": [
    { name: "Cross-Domain Mashup Ideas", slug: "cross-domain-mashup-ideas" },
    { name: "Thought Experiments & Paradoxes", slug: "thought-experiments-paradoxes" },
    { name: "Futurism & Speculative Concepts", slug: "futurism-speculative-concepts" },
    { name: "Social Experiments & Behavioral Ideas", slug: "social-experiments-behavioral-ideas" },
    { name: "Unconventional Business Models", slug: "unconventional-business-models" },
    { name: "Satirical & Provocative Concepts", slug: "satirical-provocative-concepts" },
    { name: "Political & Governance Innovations", slug: "political-governance-innovations" },
    { name: "Space & Frontier Technology Concepts", slug: "space-frontier-technology-concepts" },
    { name: "Environmental & Climate Ideas", slug: "environmental-climate-ideas" },
    { name: "Cultural & Societal Innovation Concepts", slug: "cultural-societal-innovation-concepts" },
    { name: "Absurd & Whimsical Ideas", slug: "absurd-whimsical-ideas" },
    { name: "Meta-Ideas (Ideas About Ideas)", slug: "meta-ideas-ideas-about-ideas" },
    { name: "Art & Science Intersections", slug: "art-science-intersections" },
    { name: "Unclassifiable & Miscellaneous", slug: "unclassifiable-miscellaneous" },
  ],
};

export const IDEA_MATURITY_LEVELS = [
  { value: "SEED", label: "Seed", description: "A raw spark — one-liner or short paragraph" },
  { value: "CONCEPT", label: "Concept", description: "Fleshed out with context, problem, and high-level solution" },
  { value: "BLUEPRINT", label: "Blueprint", description: "Detailed execution plan, market analysis, or technical spec" },
  { value: "PROTOTYPE_READY", label: "Prototype-Ready", description: "Includes wireframes, mockups, pseudocode, or working models" },
] as const;

// Helper to get category by slug
export function getCategoryBySlug(slug: string) {
  return Object.values(CATEGORY_META).find((c) => c.slug === slug) ?? null;
}

// Helper to get all category slugs
export function getAllCategorySlugs() {
  return Object.values(CATEGORY_META).map((c) => c.slug);
}

// Helper to get subcategories for a given category name
export function getSubcategoriesByCategory(categoryName: string) {
  return SUBCATEGORIES[categoryName] ?? [];
}

// Helper to find a subcategory by slug across all categories
export function getSubcategoryBySlug(slug: string) {
  for (const subs of Object.values(SUBCATEGORIES)) {
    const found = subs.find((s) => s.slug === slug);
    if (found) return found;
  }
  return null;
}

export const ITEMS_PER_PAGE = 12;
export const PLATFORM_FEE_PERCENT = 15;
