import type { PrismaClient } from '@prisma/client';

const CATEGORY_DATA: Array<{
  name: string;
  slug: string;
  description: string;
  icon: string;
  sortOrder: number;
  subcategories: Array<{ name: string; slug: string; sortOrder: number }>;
}> = [
  {
    name: 'Startup & Business Ideas',
    slug: 'startup-business-ideas',
    description: 'Venture concepts, business models, and entrepreneurial strategies from experienced operators.',
    icon: 'Rocket',
    sortOrder: 1,
    subcategories: [
      { name: 'SaaS Business Ideas', slug: 'saas-business-ideas', sortOrder: 1 },
      { name: 'Marketplace & Platform Concepts', slug: 'marketplace-platform-concepts', sortOrder: 2 },
      { name: 'Subscription Business Models', slug: 'subscription-business-models', sortOrder: 3 },
      { name: 'Franchise & Licensing Concepts', slug: 'franchise-licensing-concepts', sortOrder: 4 },
      { name: 'Social Enterprise & Impact Ventures', slug: 'social-enterprise-impact-ventures', sortOrder: 5 },
      { name: 'Local & Small Business Ideas', slug: 'local-small-business-ideas', sortOrder: 6 },
      { name: 'E-Commerce & DTC Concepts', slug: 'ecommerce-dtc-concepts', sortOrder: 7 },
      { name: 'Service-Based Business Models', slug: 'service-based-business-models', sortOrder: 8 },
      { name: 'B2B Business Ideas', slug: 'b2b-business-ideas', sortOrder: 9 },
      { name: 'Micro-Business & Side Hustle Concepts', slug: 'micro-business-side-hustle-concepts', sortOrder: 10 },
      { name: 'Industry Disruption Strategies', slug: 'industry-disruption-strategies', sortOrder: 11 },
      { name: 'Partnership & Joint Venture Frameworks', slug: 'partnership-joint-venture-frameworks', sortOrder: 12 },
      { name: 'Pivot & Repositioning Strategies', slug: 'pivot-repositioning-strategies', sortOrder: 13 },
      { name: 'Niche Market Opportunities', slug: 'niche-market-opportunities', sortOrder: 14 },
      { name: 'Business Model Innovations', slug: 'business-model-innovations', sortOrder: 15 },
    ],
  },
  {
    name: 'Product & Invention',
    slug: 'product-invention',
    description: 'Physical products, consumer electronics, hardware, and innovative invention concepts.',
    icon: 'Package',
    sortOrder: 2,
    subcategories: [
      { name: 'Physical Product Concepts', slug: 'physical-product-concepts', sortOrder: 1 },
      { name: 'Consumer Electronics Ideas', slug: 'consumer-electronics-ideas', sortOrder: 2 },
      { name: 'Hardware & IoT Inventions', slug: 'hardware-iot-inventions', sortOrder: 3 },
      { name: 'Sustainable & Eco Products', slug: 'sustainable-eco-products', sortOrder: 4 },
      { name: 'Food & Beverage Concepts', slug: 'food-beverage-concepts', sortOrder: 5 },
      { name: 'Fashion & Wearable Ideas', slug: 'fashion-wearable-ideas', sortOrder: 6 },
      { name: 'Home & Living Products', slug: 'home-living-products', sortOrder: 7 },
      { name: 'Toy & Game Inventions', slug: 'toy-game-inventions', sortOrder: 8 },
      { name: 'Medical Device Concepts', slug: 'medical-device-concepts', sortOrder: 9 },
      { name: 'Packaging & Material Innovations', slug: 'packaging-material-innovations', sortOrder: 10 },
      { name: 'Digital Product Ideas', slug: 'digital-product-ideas', sortOrder: 11 },
      { name: 'Accessibility & Assistive Products', slug: 'accessibility-assistive-products', sortOrder: 12 },
      { name: 'Pet & Animal Products', slug: 'pet-animal-products', sortOrder: 13 },
      { name: 'Travel & Outdoor Gear Concepts', slug: 'travel-outdoor-gear-concepts', sortOrder: 14 },
    ],
  },
  {
    name: 'Software & Technology',
    slug: 'software-technology',
    description: 'Cutting-edge tech insights, architecture patterns, scripts, and engineering strategies from industry professionals.',
    icon: 'Code',
    sortOrder: 3,
    subcategories: [
      { name: 'Mobile App Ideas', slug: 'mobile-app-ideas', sortOrder: 1 },
      { name: 'Web Application Concepts', slug: 'web-application-concepts', sortOrder: 2 },
      { name: 'Micro-SaaS Ideas', slug: 'micro-saas-ideas', sortOrder: 3 },
      { name: 'Developer Tools & Libraries', slug: 'developer-tools-libraries', sortOrder: 4 },
      { name: 'API & Integration Concepts', slug: 'api-integration-concepts', sortOrder: 5 },
      { name: 'Browser Extension Ideas', slug: 'browser-extension-ideas', sortOrder: 6 },
      { name: 'Database & Architecture Patterns', slug: 'database-architecture-patterns', sortOrder: 7 },
      { name: 'Algorithm & Data Structure Innovations', slug: 'algorithm-data-structure-innovations', sortOrder: 8 },
      { name: 'Cybersecurity Concepts', slug: 'cybersecurity-concepts', sortOrder: 9 },
      { name: 'DevOps & Infrastructure Ideas', slug: 'devops-infrastructure-ideas', sortOrder: 10 },
      { name: 'Open-Source Project Concepts', slug: 'open-source-project-concepts', sortOrder: 11 },
      { name: 'No-Code & Low-Code Solutions', slug: 'no-code-low-code-solutions', sortOrder: 12 },
      { name: 'Desktop Software Ideas', slug: 'desktop-software-ideas', sortOrder: 13 },
      { name: 'CLI & Automation Tool Concepts', slug: 'cli-automation-tool-concepts', sortOrder: 14 },
      { name: 'Gaming & Interactive Software', slug: 'gaming-interactive-software', sortOrder: 15 },
      { name: 'Search & Discovery Systems', slug: 'search-discovery-systems', sortOrder: 16 },
    ],
  },
  {
    name: 'AI & Automation',
    slug: 'ai-automation',
    description: 'AI applications, prompt engineering, agents, automation workflows, and machine learning concepts.',
    icon: 'Bot',
    sortOrder: 4,
    subcategories: [
      { name: 'AI Application Ideas', slug: 'ai-application-ideas', sortOrder: 1 },
      { name: 'Prompt Engineering & Prompt Libraries', slug: 'prompt-engineering-prompt-libraries', sortOrder: 2 },
      { name: 'AI Agent & Workflow Concepts', slug: 'ai-agent-workflow-concepts', sortOrder: 3 },
      { name: 'Machine Learning Model Ideas', slug: 'machine-learning-model-ideas', sortOrder: 4 },
      { name: 'Natural Language Processing Concepts', slug: 'natural-language-processing-concepts', sortOrder: 5 },
      { name: 'Computer Vision Applications', slug: 'computer-vision-applications', sortOrder: 6 },
      { name: 'Generative AI Use Cases', slug: 'generative-ai-use-cases', sortOrder: 7 },
      { name: 'AI-Powered Business Tools', slug: 'ai-powered-business-tools', sortOrder: 8 },
      { name: 'Chatbot & Conversational AI Ideas', slug: 'chatbot-conversational-ai-ideas', sortOrder: 9 },
      { name: 'Robotic Process Automation (RPA)', slug: 'robotic-process-automation-rpa', sortOrder: 10 },
      { name: 'AI for Creative Industries', slug: 'ai-for-creative-industries', sortOrder: 11 },
      { name: 'Data Pipeline & ETL Concepts', slug: 'data-pipeline-etl-concepts', sortOrder: 12 },
      { name: 'Predictive Analytics Frameworks', slug: 'predictive-analytics-frameworks', sortOrder: 13 },
      { name: 'AI Ethics & Governance Frameworks', slug: 'ai-ethics-governance-frameworks', sortOrder: 14 },
      { name: 'Voice AI & Speech Applications', slug: 'voice-ai-speech-applications', sortOrder: 15 },
      { name: 'AI Training Data Strategies', slug: 'ai-training-data-strategies', sortOrder: 16 },
    ],
  },
  {
    name: 'Marketing & Growth',
    slug: 'marketing-growth',
    description: 'Growth hacks, SEO tactics, conversion strategies, and campaign insights from top marketers.',
    icon: 'TrendingUp',
    sortOrder: 5,
    subcategories: [
      { name: 'Growth Hacking Strategies', slug: 'growth-hacking-strategies', sortOrder: 1 },
      { name: 'Viral Marketing Concepts', slug: 'viral-marketing-concepts', sortOrder: 2 },
      { name: 'SEO & Organic Growth Frameworks', slug: 'seo-organic-growth-frameworks', sortOrder: 3 },
      { name: 'Email Marketing Strategies', slug: 'email-marketing-strategies', sortOrder: 4 },
      { name: 'Social Media Campaign Ideas', slug: 'social-media-campaign-ideas', sortOrder: 5 },
      { name: 'Influencer Marketing Concepts', slug: 'influencer-marketing-concepts', sortOrder: 6 },
      { name: 'Community-Led Growth Strategies', slug: 'community-led-growth-strategies', sortOrder: 7 },
      { name: 'Referral & Affiliate Program Designs', slug: 'referral-affiliate-program-designs', sortOrder: 8 },
      { name: 'Paid Advertising Strategies', slug: 'paid-advertising-strategies', sortOrder: 9 },
      { name: 'Product-Led Growth Frameworks', slug: 'product-led-growth-frameworks', sortOrder: 10 },
      { name: 'Content Marketing Systems', slug: 'content-marketing-systems', sortOrder: 11 },
      { name: 'Conversion Optimization Ideas', slug: 'conversion-optimization-ideas', sortOrder: 12 },
      { name: 'Launch & Go-to-Market Strategies', slug: 'launch-go-to-market-strategies', sortOrder: 13 },
      { name: 'Guerrilla & Unconventional Marketing', slug: 'guerrilla-unconventional-marketing', sortOrder: 14 },
      { name: 'Retention & Loyalty Strategies', slug: 'retention-loyalty-strategies', sortOrder: 15 },
      { name: 'Partnership & Co-Marketing Ideas', slug: 'partnership-co-marketing-ideas', sortOrder: 16 },
    ],
  },
  {
    name: 'Branding & Identity',
    slug: 'branding-identity',
    description: 'Brand positioning, naming, visual identity, and strategic brand development concepts.',
    icon: 'Fingerprint',
    sortOrder: 6,
    subcategories: [
      { name: 'Brand Name & Naming Concepts', slug: 'brand-name-naming-concepts', sortOrder: 1 },
      { name: 'Brand Positioning Strategies', slug: 'brand-positioning-strategies', sortOrder: 2 },
      { name: 'Tagline & Slogan Ideas', slug: 'tagline-slogan-ideas', sortOrder: 3 },
      { name: 'Brand Story & Narrative Frameworks', slug: 'brand-story-narrative-frameworks', sortOrder: 4 },
      { name: 'Visual Identity Directions', slug: 'visual-identity-directions', sortOrder: 5 },
      { name: 'Brand Architecture Strategies', slug: 'brand-architecture-strategies', sortOrder: 6 },
      { name: 'Tone of Voice Frameworks', slug: 'tone-of-voice-frameworks', sortOrder: 7 },
      { name: 'Rebranding & Refresh Strategies', slug: 'rebranding-refresh-strategies', sortOrder: 8 },
      { name: 'Personal Branding Frameworks', slug: 'personal-branding-frameworks', sortOrder: 9 },
      { name: 'Cultural & Purpose-Driven Branding', slug: 'cultural-purpose-driven-branding', sortOrder: 10 },
      { name: 'Luxury & Premium Brand Concepts', slug: 'luxury-premium-brand-concepts', sortOrder: 11 },
      { name: 'Brand Experience & Sensory Design', slug: 'brand-experience-sensory-design', sortOrder: 12 },
      { name: 'Employer Branding Strategies', slug: 'employer-branding-strategies', sortOrder: 13 },
    ],
  },
  {
    name: 'Content & Creator Economy',
    slug: 'content-creator-economy',
    description: 'Content creation secrets, audience growth strategies, and creator monetization insights.',
    icon: 'Video',
    sortOrder: 7,
    subcategories: [
      { name: 'YouTube Channel Concepts', slug: 'youtube-channel-concepts', sortOrder: 1 },
      { name: 'Podcast Ideas & Formats', slug: 'podcast-ideas-formats', sortOrder: 2 },
      { name: 'Newsletter & Publication Concepts', slug: 'newsletter-publication-concepts', sortOrder: 3 },
      { name: 'TikTok & Short-Form Content Strategies', slug: 'tiktok-short-form-content-strategies', sortOrder: 4 },
      { name: 'Creator Monetization Models', slug: 'creator-monetization-models', sortOrder: 5 },
      { name: 'Online Community Concepts', slug: 'online-community-concepts', sortOrder: 6 },
      { name: 'Digital Course & Workshop Ideas', slug: 'digital-course-workshop-ideas', sortOrder: 7 },
      { name: 'Membership & Patreon-Style Models', slug: 'membership-patreon-style-models', sortOrder: 8 },
      { name: 'Content Repurposing Frameworks', slug: 'content-repurposing-frameworks', sortOrder: 9 },
      { name: 'Audience Building Strategies', slug: 'audience-building-strategies', sortOrder: 10 },
      { name: 'Live Streaming Concepts', slug: 'live-streaming-concepts', sortOrder: 11 },
      { name: 'UGC & Collaborative Content Ideas', slug: 'ugc-collaborative-content-ideas', sortOrder: 12 },
      { name: 'Content Calendar & Scheduling Systems', slug: 'content-calendar-scheduling-systems', sortOrder: 13 },
      { name: 'Creator Tool & Platform Ideas', slug: 'creator-tool-platform-ideas', sortOrder: 14 },
      { name: 'Sponsorship & Brand Deal Frameworks', slug: 'sponsorship-brand-deal-frameworks', sortOrder: 15 },
    ],
  },
  {
    name: 'Writing & Storytelling',
    slug: 'writing-storytelling',
    description: 'Novel concepts, screenplay ideas, worldbuilding, narrative structures, and copywriting frameworks.',
    icon: 'PenTool',
    sortOrder: 8,
    subcategories: [
      { name: 'Novel & Book Concepts', slug: 'novel-book-concepts', sortOrder: 1 },
      { name: 'Screenplay & Script Ideas', slug: 'screenplay-script-ideas', sortOrder: 2 },
      { name: 'Short Story Seeds', slug: 'short-story-seeds', sortOrder: 3 },
      { name: 'Worldbuilding & Universe Designs', slug: 'worldbuilding-universe-designs', sortOrder: 4 },
      { name: 'Character Concepts & Archetypes', slug: 'character-concepts-archetypes', sortOrder: 5 },
      { name: 'Plot Structures & Narrative Blueprints', slug: 'plot-structures-narrative-blueprints', sortOrder: 6 },
      { name: 'Poetry & Lyrical Concepts', slug: 'poetry-lyrical-concepts', sortOrder: 7 },
      { name: 'Non-Fiction Book Ideas', slug: 'non-fiction-book-ideas', sortOrder: 8 },
      { name: 'Comedy & Satire Concepts', slug: 'comedy-satire-concepts', sortOrder: 9 },
      { name: 'Interactive & Branching Narrative Ideas', slug: 'interactive-branching-narrative-ideas', sortOrder: 10 },
      { name: 'Copywriting Frameworks', slug: 'copywriting-frameworks', sortOrder: 11 },
      { name: 'Journalism & Essay Concepts', slug: 'journalism-essay-concepts', sortOrder: 12 },
      { name: 'Game Narrative & Lore Concepts', slug: 'game-narrative-lore-concepts', sortOrder: 13 },
      { name: 'Speech & Presentation Frameworks', slug: 'speech-presentation-frameworks', sortOrder: 14 },
      { name: 'Anthology & Series Structures', slug: 'anthology-series-structures', sortOrder: 15 },
    ],
  },
  {
    name: 'Design & Visual Arts',
    slug: 'design-visual-arts',
    description: 'UX patterns, creative workflows, design systems, and visual strategies from seasoned designers.',
    icon: 'Palette',
    sortOrder: 9,
    subcategories: [
      { name: 'UI/UX Design Concepts', slug: 'ui-ux-design-concepts', sortOrder: 1 },
      { name: 'Graphic Design Directions', slug: 'graphic-design-directions', sortOrder: 2 },
      { name: 'Illustration & Art Concepts', slug: 'illustration-art-concepts', sortOrder: 3 },
      { name: 'Motion Design & Animation Ideas', slug: 'motion-design-animation-ideas', sortOrder: 4 },
      { name: '3D & Spatial Design Concepts', slug: '3d-spatial-design-concepts', sortOrder: 5 },
      { name: 'Photography Project Ideas', slug: 'photography-project-ideas', sortOrder: 6 },
      { name: 'Architecture & Interior Design Concepts', slug: 'architecture-interior-design-concepts', sortOrder: 7 },
      { name: 'Fashion & Textile Design Ideas', slug: 'fashion-textile-design-ideas', sortOrder: 8 },
      { name: 'Design System Frameworks', slug: 'design-system-frameworks', sortOrder: 9 },
      { name: 'Generative & Algorithmic Art Concepts', slug: 'generative-algorithmic-art-concepts', sortOrder: 10 },
      { name: 'Typographic & Lettering Concepts', slug: 'typographic-lettering-concepts', sortOrder: 11 },
      { name: 'Environmental & Experience Design', slug: 'environmental-experience-design', sortOrder: 12 },
      { name: 'Data Visualization Ideas', slug: 'data-visualization-ideas', sortOrder: 13 },
      { name: 'Game Art & Asset Concepts', slug: 'game-art-asset-concepts', sortOrder: 14 },
    ],
  },
  {
    name: 'Music & Audio',
    slug: 'music-audio',
    description: 'Song concepts, production techniques, audio branding, and music business models.',
    icon: 'Music',
    sortOrder: 10,
    subcategories: [
      { name: 'Song & Composition Concepts', slug: 'song-composition-concepts', sortOrder: 1 },
      { name: 'Album & EP Themes', slug: 'album-ep-themes', sortOrder: 2 },
      { name: 'Sound Design Ideas', slug: 'sound-design-ideas', sortOrder: 3 },
      { name: 'Audio Branding & Sonic Logos', slug: 'audio-branding-sonic-logos', sortOrder: 4 },
      { name: 'Music Production Techniques', slug: 'music-production-techniques', sortOrder: 5 },
      { name: 'Film & Game Scoring Concepts', slug: 'film-game-scoring-concepts', sortOrder: 6 },
      { name: 'Podcast Audio Formats', slug: 'podcast-audio-formats', sortOrder: 7 },
      { name: 'Music Business & Label Models', slug: 'music-business-label-models', sortOrder: 8 },
      { name: 'AI Music & Generative Audio Ideas', slug: 'ai-music-generative-audio-ideas', sortOrder: 9 },
      { name: 'Live Performance Concepts', slug: 'live-performance-concepts', sortOrder: 10 },
      { name: 'Music Collaboration Frameworks', slug: 'music-collaboration-frameworks', sortOrder: 11 },
      { name: 'Sample & Loop Library Concepts', slug: 'sample-loop-library-concepts', sortOrder: 12 },
    ],
  },
  {
    name: 'Web3 & Blockchain',
    slug: 'web3-blockchain',
    description: 'Token models, DeFi protocols, DAOs, NFTs, and decentralized application concepts.',
    icon: 'Link',
    sortOrder: 11,
    subcategories: [
      { name: 'Token & Tokenomics Models', slug: 'token-tokenomics-models', sortOrder: 1 },
      { name: 'DeFi Protocol Concepts', slug: 'defi-protocol-concepts', sortOrder: 2 },
      { name: 'DAO Structures & Governance Models', slug: 'dao-structures-governance-models', sortOrder: 3 },
      { name: 'NFT Utility & Collection Ideas', slug: 'nft-utility-collection-ideas', sortOrder: 4 },
      { name: 'Smart Contract Concepts', slug: 'smart-contract-concepts', sortOrder: 5 },
      { name: 'Decentralized App (dApp) Ideas', slug: 'decentralized-app-dapp-ideas', sortOrder: 6 },
      { name: 'Blockchain Gaming Concepts', slug: 'blockchain-gaming-concepts', sortOrder: 7 },
      { name: 'Digital Identity & Reputation Systems', slug: 'digital-identity-reputation-systems', sortOrder: 8 },
      { name: 'Decentralized Social Media Concepts', slug: 'decentralized-social-media-concepts', sortOrder: 9 },
      { name: 'Real-World Asset (RWA) Tokenization Ideas', slug: 'real-world-asset-rwa-tokenization-ideas', sortOrder: 10 },
      { name: 'Cross-Chain & Interoperability Concepts', slug: 'cross-chain-interoperability-concepts', sortOrder: 11 },
      { name: 'Privacy & Zero-Knowledge Applications', slug: 'privacy-zero-knowledge-applications', sortOrder: 12 },
      { name: 'Creator Royalty & Licensing Models', slug: 'creator-royalty-licensing-models', sortOrder: 13 },
    ],
  },
  {
    name: 'Finance & Monetization',
    slug: 'finance-monetization',
    description: 'Investment strategies, financial planning insights, revenue models, and money management tactics.',
    icon: 'DollarSign',
    sortOrder: 12,
    subcategories: [
      { name: 'Revenue Model Blueprints', slug: 'revenue-model-blueprints', sortOrder: 1 },
      { name: 'Pricing Strategy Frameworks', slug: 'pricing-strategy-frameworks', sortOrder: 2 },
      { name: 'Fintech Product Concepts', slug: 'fintech-product-concepts', sortOrder: 3 },
      { name: 'Investment & Trading Theses', slug: 'investment-trading-theses', sortOrder: 4 },
      { name: 'Passive Income Models', slug: 'passive-income-models', sortOrder: 5 },
      { name: 'Crowdfunding & Fundraising Strategies', slug: 'crowdfunding-fundraising-strategies', sortOrder: 6 },
      { name: 'Real Estate Investment Concepts', slug: 'real-estate-investment-concepts', sortOrder: 7 },
      { name: 'Paywall & Gating Strategies', slug: 'paywall-gating-strategies', sortOrder: 8 },
      { name: 'Freemium & Upselling Frameworks', slug: 'freemium-upselling-frameworks', sortOrder: 9 },
      { name: 'Financial Literacy & Tool Ideas', slug: 'financial-literacy-tool-ideas', sortOrder: 10 },
      { name: 'Insurance & Risk Model Concepts', slug: 'insurance-risk-model-concepts', sortOrder: 11 },
      { name: 'Multi-Sided Marketplace Economics', slug: 'multi-sided-marketplace-economics', sortOrder: 12 },
      { name: 'Unit Economics Frameworks', slug: 'unit-economics-frameworks', sortOrder: 13 },
    ],
  },
  {
    name: 'Education & Knowledge',
    slug: 'education-knowledge',
    description: 'Teaching methods, curriculum insights, and learning frameworks from education professionals.',
    icon: 'GraduationCap',
    sortOrder: 13,
    subcategories: [
      { name: 'Online Course Concepts', slug: 'online-course-concepts', sortOrder: 1 },
      { name: 'EdTech Product Ideas', slug: 'edtech-product-ideas', sortOrder: 2 },
      { name: 'Curriculum & Syllabus Designs', slug: 'curriculum-syllabus-designs', sortOrder: 3 },
      { name: 'Workshop & Bootcamp Formats', slug: 'workshop-bootcamp-formats', sortOrder: 4 },
      { name: 'Learning Gamification Frameworks', slug: 'learning-gamification-frameworks', sortOrder: 5 },
      { name: 'Corporate Training Concepts', slug: 'corporate-training-concepts', sortOrder: 6 },
      { name: 'Children & Youth Education Ideas', slug: 'children-youth-education-ideas', sortOrder: 7 },
      { name: 'Tutoring & Mentorship Models', slug: 'tutoring-mentorship-models', sortOrder: 8 },
      { name: 'Language Learning Concepts', slug: 'language-learning-concepts', sortOrder: 9 },
      { name: 'Knowledge Management Systems', slug: 'knowledge-management-systems', sortOrder: 10 },
      { name: 'Research & Academic Frameworks', slug: 'research-academic-frameworks', sortOrder: 11 },
      { name: 'Skill Assessment & Certification Ideas', slug: 'skill-assessment-certification-ideas', sortOrder: 12 },
      { name: 'Micro-Learning & Bite-Size Content Systems', slug: 'micro-learning-bite-size-content-systems', sortOrder: 13 },
    ],
  },
  {
    name: 'Health & Wellness',
    slug: 'health-wellness',
    description: 'Wellness insights, fitness strategies, health optimization tips, and mental health innovations.',
    icon: 'Heart',
    sortOrder: 14,
    subcategories: [
      { name: 'HealthTech & MedTech Concepts', slug: 'healthtech-medtech-concepts', sortOrder: 1 },
      { name: 'Mental Health & Therapy Innovations', slug: 'mental-health-therapy-innovations', sortOrder: 2 },
      { name: 'Fitness & Exercise Program Ideas', slug: 'fitness-exercise-program-ideas', sortOrder: 3 },
      { name: 'Nutrition & Diet Frameworks', slug: 'nutrition-diet-frameworks', sortOrder: 4 },
      { name: 'Sleep & Recovery Concepts', slug: 'sleep-recovery-concepts', sortOrder: 5 },
      { name: 'Wellness App Ideas', slug: 'wellness-app-ideas', sortOrder: 6 },
      { name: 'Mindfulness & Meditation Concepts', slug: 'mindfulness-meditation-concepts', sortOrder: 7 },
      { name: 'Corporate Wellness Programs', slug: 'corporate-wellness-programs', sortOrder: 8 },
      { name: 'Telehealth & Remote Care Models', slug: 'telehealth-remote-care-models', sortOrder: 9 },
      { name: 'Wearable Health Concepts', slug: 'wearable-health-concepts', sortOrder: 10 },
      { name: 'Longevity & Biohacking Frameworks', slug: 'longevity-biohacking-frameworks', sortOrder: 11 },
      { name: 'Holistic & Alternative Wellness Ideas', slug: 'holistic-alternative-wellness-ideas', sortOrder: 12 },
    ],
  },
  {
    name: 'Personal Development & Lifestyle',
    slug: 'personal-development-lifestyle',
    description: 'Productivity systems, habit design, goal-setting, career strategy, and life design concepts.',
    icon: 'Compass',
    sortOrder: 15,
    subcategories: [
      { name: 'Productivity Systems & Frameworks', slug: 'productivity-systems-frameworks', sortOrder: 1 },
      { name: 'Habit Design & Behavior Change Models', slug: 'habit-design-behavior-change-models', sortOrder: 2 },
      { name: 'Goal-Setting & Planning Frameworks', slug: 'goal-setting-planning-frameworks', sortOrder: 3 },
      { name: 'Career Strategy & Transition Ideas', slug: 'career-strategy-transition-ideas', sortOrder: 4 },
      { name: 'Relationship & Communication Frameworks', slug: 'relationship-communication-frameworks', sortOrder: 5 },
      { name: 'Financial Independence & FIRE Strategies', slug: 'financial-independence-fire-strategies', sortOrder: 6 },
      { name: 'Journaling & Reflection Systems', slug: 'journaling-reflection-systems', sortOrder: 7 },
      { name: 'Time Management Architectures', slug: 'time-management-architectures', sortOrder: 8 },
      { name: 'Decision-Making Frameworks', slug: 'decision-making-frameworks', sortOrder: 9 },
      { name: 'Travel & Nomad Lifestyle Concepts', slug: 'travel-nomad-lifestyle-concepts', sortOrder: 10 },
      { name: 'Minimalism & Intentional Living Ideas', slug: 'minimalism-intentional-living-ideas', sortOrder: 11 },
      { name: 'Parenting & Family Frameworks', slug: 'parenting-family-frameworks', sortOrder: 12 },
      { name: 'Networking & Social Capital Strategies', slug: 'networking-social-capital-strategies', sortOrder: 13 },
      { name: 'Philosophy & Life Design Concepts', slug: 'philosophy-life-design-concepts', sortOrder: 14 },
    ],
  },
  {
    name: 'Experimental & Wildcard',
    slug: 'experimental-wildcard',
    description: 'Cross-domain mashups, thought experiments, futurism, and ideas that defy classification.',
    icon: 'Sparkles',
    sortOrder: 16,
    subcategories: [
      { name: 'Cross-Domain Mashup Ideas', slug: 'cross-domain-mashup-ideas', sortOrder: 1 },
      { name: 'Thought Experiments & Paradoxes', slug: 'thought-experiments-paradoxes', sortOrder: 2 },
      { name: 'Futurism & Speculative Concepts', slug: 'futurism-speculative-concepts', sortOrder: 3 },
      { name: 'Social Experiments & Behavioral Ideas', slug: 'social-experiments-behavioral-ideas', sortOrder: 4 },
      { name: 'Unconventional Business Models', slug: 'unconventional-business-models', sortOrder: 5 },
      { name: 'Satirical & Provocative Concepts', slug: 'satirical-provocative-concepts', sortOrder: 6 },
      { name: 'Political & Governance Innovations', slug: 'political-governance-innovations', sortOrder: 7 },
      { name: 'Space & Frontier Technology Concepts', slug: 'space-frontier-technology-concepts', sortOrder: 8 },
      { name: 'Environmental & Climate Ideas', slug: 'environmental-climate-ideas', sortOrder: 9 },
      { name: 'Cultural & Societal Innovation Concepts', slug: 'cultural-societal-innovation-concepts', sortOrder: 10 },
      { name: 'Absurd & Whimsical Ideas', slug: 'absurd-whimsical-ideas', sortOrder: 11 },
      { name: 'Meta-Ideas (Ideas About Ideas)', slug: 'meta-ideas-ideas-about-ideas', sortOrder: 12 },
      { name: 'Art & Science Intersections', slug: 'art-science-intersections', sortOrder: 13 },
      { name: 'Unclassifiable & Miscellaneous', slug: 'unclassifiable-miscellaneous', sortOrder: 14 },
    ],
  },
];

export async function seedCategories(prisma: PrismaClient) {
  console.log('🌱 Seeding categories and subcategories...');

  for (const cat of CATEGORY_DATA) {
    const { subcategories, ...categoryData } = cat;

    const category = await prisma.category.upsert({
      where: { slug: cat.slug },
      update: {
        name: categoryData.name,
        description: categoryData.description,
        icon: categoryData.icon,
        sortOrder: categoryData.sortOrder,
      },
      create: categoryData,
    });

    for (const sub of subcategories) {
      await prisma.subcategory.upsert({
        where: { slug: sub.slug },
        update: {
          name: sub.name,
          sortOrder: sub.sortOrder,
        },
        create: {
          ...sub,
          categoryId: category.id,
        },
      });
    }
  }

  const categoryCount = CATEGORY_DATA.length;
  const subcategoryCount = CATEGORY_DATA.reduce((acc, cat) => acc + cat.subcategories.length, 0);
  console.log(`✅ Seeded ${categoryCount} categories and ${subcategoryCount} subcategories`);
}
